
stages:          
  - build

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

run-mixed-crops-example:
  stage: build
  tags:
    - sifmap-runner
  only: 
    - main
  script:
    - docker info
    - docker build --build-arg SERVER=$SERVER -t $IMAGE_TAG
      -t $CI_REGISTRY_IMAGE:latest
      -f ./docker/Dockerfile
      --build-arg CI_COMMIT_SHA
      --build-arg CI_PROJECT_URL
      --build-arg CI_COMMIT_TIME
      --build-arg CI_JOB_URL 
      --build-arg GITLAB_USER_LOGIN
      --build-arg GITLAB_USER_NAME .
    - docker push $IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:latest

build-sifmapviewer:
  stage: build
  tags:
    - sifmap-runner
  only:
    - SIFMapViewer
  script:
    - docker info
    - docker build --build-arg SERVER=$SERVER -t $IMAGE_TAG
      -t $CI_REGISTRY_IMAGE:sifmapviewer-latest
      -f ./docker/Dockerfile
      --build-arg CI_COMMIT_SHA
      --build-arg CI_PROJECT_URL
      --build-arg CI_COMMIT_TIME
      --build-arg CI_JOB_URL 
      --build-arg GITLAB_USER_LOGIN
      --build-arg GITLAB_USER_NAME .
    - docker push $IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:sifmapviewer-latest
