# SPDX-FileCopyrightText: © 2025 Forschungszentrum Jülich GmbH
# SPDX-FileContributor: Armagan Elibol
# SPDX-FileContributor: Christian Hirt
# SPDX-FileContributor: Jim Buffat <j.buffat@fz-juelich.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later


# Default values for incomplete configuration files. Refer to CONFIGURATION.md for a detailed explanation of each
# parameter.

data_params:
  dataset_path: ""
  result_path: ""
  camera_regex:
    '760': '.*?(C1).*'
    '757': '.*?(C2).*'
  datatake_regex: '.*?(\d+)\.tif$'


sensor_calibration_config: 'sensor_calib.yaml'


preprocessing_params:
  load_data: false
  load_features: false
  write: true
  keep_data_in_memory: false
  ransac_residual_threshold: 1
  pairing_min_samples: 16
  pairing_transform_type: 'projective'
  pairing_master_band: 'Rad757'
  pairing_optical_flow_refinement: 'farneback'
  interpolation_method: 'cubic'
  rescale_interpolation_method: null
  sif_computation_method: 'fld'
  radiance_gaussian_blur:
    '760': null
    '757': null


registration_params:
  load: false
  write: true
  n_features_trial: 128
  min_n_correspondences: 8
  min_movement: null
  ransac_residual_threshold: 10
  close_images_limit: 1
  protect_correspondences_in_close_images: 0
  spread_points: true


alignment_params:
  load: false
  write: true
  n_outlier_removal: 5
  outlier_threshold: 5
  manual_outlier_mode: false
  n_points: 16
  resume_optimization: false
  remove_disconnected_threshold: 4
  optim_params:
    xtol: 0.0000001
    ftol: 0.000001
    gtol: 1000
    max_nfev: 75
    lsmr_maxiter: 300
    lsmr_dynamic_maxiter_factor: null
    lsmr_max_maxiter: null 


feature_params:
  n_SIFT_features_per_image: 5096
  n_features_threshold: 64
  feature_product: "Rad757"
  mask: null


parallel_params:
  do_parallel: true
  n_processes: 32
  n_threads: 24


vis_params:
  run: true
  interpolation_method: 'cubic'
  n_processes: 10
  products: [ 'sif', 'ref757', 'ref760' ]
  aggregation_methods: [ 'closest_dist_weighted' ]
  mosaic_origin:
    X: 0
    Y: 0
  mosaic_resolution: 1


flann_params:
  algorithm: 1
  trees: 5
  checks: 50
  type: "FlannBasedMatcher"

