# SPDX-FileCopyrightText: © 2025 Forschungszentrum Jülich GmbH
# SPDX-FileContributor: Armagan Elibol
# SPDX-FileContributor: Christian Hirt
# SPDX-FileContributor: Jim Buffat <j.buffat@fz-juelich.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Data params
data_params:
  dataset_path: ""
  result_path: ""
  camera_regex:
    '760': '.*?(C760).*?\.tif$'
    '757': '.*?(C757).*?\.tif$'
  datatake_regex: '.*?'


# Sensor calibration configuration
sensor_calibration_config: ''


preprocessing_params:
  load_data: false
  load_features: false
  write: true
  keep_data_in_memory: false

  ransac_residual_threshold: 0.5
  pairing_min_samples: 30
  pairing_transform_type: 'projective'
  pairing_finetune_metric: null  # 'laplace'  # 'mi'
  pairing_master_band: 'Rad757'

  radiance_gaussian_blur: null

  interpolation_method: 'linear'
  rescale_interpolation_method: null


registration_params:
  load: false
  write: true
  min_n_correspondences: 10         # keep image pair if there are at least min_n_correspondences
  min_movement: 6
  ransac_residual_threshold: 1


alignment_params:
  load: false
  write: true
  case: 4                           # 1: 2d w/o outlier removal (or), 2: 2d w. or, 3: 3d w/o or, 4: 3d w. or
  n_outlier_removal: 1             # if manual_residual_removal is false, iterate n_outlier_removal times
  outlier_threshold: 5
  manual_outlier_mode: false        # allow manual mode for residual based removal
  n_points: 30                      # maximum number of correspondences per image pair to be used
  resume_optimization: false
  optim_params:
    xtol: 0.0001
    ftol: 0.000001
    x_scale: 'jac'


# Feature creation params
feature_params:
  n_features_trial: 250             # number of features per image
  n_SIFT_features_per_image: 20000  # sample n_SIFT_features_per_image SIFT features in each image
  n_features_threshold: 100         # drop an image if less than n_features_threshold SIFT features are found
  feature_product: "Rad757"
  mask: null


# Parallelization params
parallel_params:
  do_parallel: true                 # setting this to false deactivates the process based parallelization but not threading
  n_processes: 64                    # -1 will use the all logical cores on your machine
  n_threads: -1                     # -1 will use numba.config.NUMBA_NUM_THREADS threads


# FLANN parameters
flann_params:
  algorithm: 1
  trees: 5
  checks: 50
  type: "FlannBasedMatcher"


# Visualization parameters
vis_params:
  mosaic_origin:
    X: 0
    Y: 0
  mosaic_resolution: 1
  interpolation_method: 'linear'
